### ISSUE TITLE
64bit client

### ISSUE THREAD

**Issue by Thaodan** [JeremyStepp/OneLauncher#28] opened 2021-08-21 23:18 UTC
Hey I've tried using the 64bit client with the included wine version and without but the client just exits after the loading screen.
Have you reports of the 64bit client working with wine?

**Comment by JeremyStepp** [comment] 2021-08-22 00:54
I've used the 64-bit client exclusively since it came out. Could you give the log from launching the game? There is a save log button after the client exits.

**Comment by Thaodan** [comment] 2021-08-22 01:10
Are you using an Nvidia GPU? I'm using AMD maybe there is something wrong in my setup I give you logs in a min.

**Comment by Thaodan** [comment] 2021-08-22 01:15
[lotro_.22.08.2021.log](https://github.com/JeremyStepp/OneLauncher/files/7026410/lotro_.22.08.2021.log)

**Comment by JeremyStepp** [comment] 2021-08-22 02:20
I do use Nvidia with the proprietary drivers. Nothing stands out to me in the log besides esync not being setup, which shouldn't make a difference here. Make sure you have WINE's dependencies installed, as explained [here](https://github.com/lutris/docs/blob/master/WineDependencies.md). There's a successful AMD report from running the game with Proton [here](https://www.protondb.com/app/212500#tDM_n9GKac). If you've used OneLauncher for a while, deleting the prefix at `~/.OneLauncher/wine/prefix` could also help. If you want to try running the game with Proton you can add LOTRO as a custom game in Steam or set WINE_URL in the WinePrefix.py file to a Proton link from https://github.com/Kron4ek/Wine-Builds/releases and uncomment the code for proton as specified in the comment above the WINE_URL. If you can run the game through Steam's Proton and not Proton with OneLauncher than there is most likely something wrong with your installed libraries, since  Steam has its own runtime.

**Comment by JeremyStepp** [comment] 2021-08-22 02:21
As far as I remember, I haven't had this issue, so all I can give is general advice.

**Comment by JeremyStepp** [comment] 2021-08-22 02:46
Based on https://www.lotro.com/forums/showthread.php?673658-64bit-client-not-getting-to-character-select and https://www.lotro.com/forums/showthread.php?687435-AMD-Threadrippers-not-getting-to-character-select-screen-using-64-bit-clients&s=b0dd1f008a76b18f37b5a75049547522 this could also be caused by having a high core count CPU.

**Comment by Thaodan** [comment] 2021-08-22 03:03
I have all wine dependencies installed since I  used wine before, 
had the error before and thought I give your setup a go.


High core count could be an issue since I have 32 real and 64 
virtual cores.
Strangely the 32bit client is not affected. I looked into the DLLs 
linked into the 64bit client and saw its linked against a much 
newer Windows SDK so that issue could be true.

**Comment by Thaodan** [comment] 2021-08-22 03:08
A look into lotroclient64.log shows why the client crashes:
[lotroclient64.log](https://github.com/JeremyStepp/OneLauncher/files/7026502/lotroclient64.log)

**Comment by JeremyStepp** [comment] 2021-08-22 03:25
Since it seems to be an issue with LOTRO I'll close this issue. Feel free to open it back up if it turns out there is something wrong on my end. Hopefully you can find a solution better than disabling cores.

**Closed by JeremyStepp** 2021-08-22 03:25 UTC
